title: "selfdriven Group"
description: "Group index"
context: "group"
baseurl: ""
url: ""
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: default
plugins:
  - jekyll-feed
  - jekyll-seo-tag
